---
title: "HW1"
author: "Lowson Li, R08323023"
output:
  html_notebook:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: simplex
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  html_document:
    df_print: paged
    toc: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```
# Load packages
```{r}
library(dplyr)
library(knitr)
library(kableExtra)
```

# Data generating proccess
```{r}
# define function 
dgp <- function(p, n, r) { # p:principal, n:number of periods, r:interest rate
  pp <<- c(rep(round(p / n), n - 1), p - round(p / n) * (n - 1)) # generate divided principal
  left <<- p - cumsum(pp) # calculate unpaid loans
  left <<- c(p, left[1:n - 1]) # adjust first element: principal
  rr <<- round(left * (r / 12)) # calculate the monthly interest
  total <<- pp + rr # total money paid
  cumsum_total <<- cumsum(total) # cummulative sum of total
  data_generated <<- data.frame( # Some data cleaning
    preiod = c(1:n),
    principal = pp,
    interest = rr,
    cumsum_total = cumsum_total
  )
}
```
# Results
```{r}
# generate data 
dgp(10000000000,24,0.07)
```
```{r}
# showing table 
data_generated %>% 
  knitr::kable() %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = F)
```


