---
title: "HW2"
author: "Lowson Li, R08323023"
output:
  html_notebook:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: simplex
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  html_document:
    df_print: paged
    toc: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```
# Strategy
1. Try to replicate the [YTM calculator](https://www.calkoo.com/en/ytm-calculator)
2. 


* For more details of the code and instructions, please visit my [Github](https://github.com/isthatlowsonli/Financial_Engineering)
 + [Source code](https://github.com/isthatlowsonli/Financial_Engineering/blob/master/Script/HW2.Rmd)
 + [Academic Profilio](https://isthatlowsonli.github.io//Financial_Engineering/Script/practice.nb.html)

# Load packages
```{r}
library(dplyr)
library(knitr)
library(kableExtra)
```

# YTM calculator 
```{r}
# define function
ytm <- function(price, par = 100, r, c, y, m) { # price:current bond price, par: bond par value(with default value $100), c: bond coupon rate, y: years to maturity, m: compounded period per year
  cash_flow <<- c(-price, rep(par * c / m, y * m - 1), par * c / m + par) # create cash flow vector
  object_function <<- function(r, cash_flow, t = seq(along = cash_flow)) sum(cash_flow / (1 + r)^t) # setting the objective function to find the YTM, represented as 'r'

  ytm_ans <<- uniroot(f = object_function, interval = c(0, 1), cash_flow = cash_flow)$root # find the root of the objective function

  return(ytm_ans)
}
```

# Results
```{r}
ytm(price = 103.72,
    c = 0.015,
    y = 10,
    m = 1)
```


